version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
