version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234567890


  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
