version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: *ваш_пользователь*
      MINIO_ROOT_PASSWORD: *ваш_пароль*
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
