version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234567890
